### PR TITLE
Fix ic-repl-based CI tests to do authentication correctly.

### PR DESCRIPTION
**Pull request by matthewhammer**
This started as another PR, but seems to require its own lifespan.

Will resolve this with help from ic-repl author @chenyan-dfinity, with some new release, likely.

### CODE REVIEW

**Comment by matthewhammer** [comment]
@chenyan-dfinity Has looked at this and has concluded that `ic-repl` needs to adapt to handle the wallet-based identity that `dfx` creates when building CanCan locally.

**Comment by chenyan-dfinity** [comment]
@matthewhammer  The error seems to be expected. There is no `abuseFlags` in `getVideoInfo`. Only `abuseFlagUsers`

**Comment by matthewhammer** [comment]
Okay, the API changed and the test was never updated.

I think the other changes you made were necessary though (`--no-wallet`).

Without that, I was getting stuck here, by getting `null` when I expected non-`null`:
  https://github.com/dfinity/cancan/pull/22/checks?check_run_id=2634472036#step:5:85
  
I didn't realize that `--no-wallet` existed or that it would help here.  Thanks!

**Comment by matthewhammer** [comment]
This is an old attempt.

Re-trying now with #25

**Pull request closed without merging**
